Update Flash Script to Use libgpiod for GPIO Control instead of deprecated /sys/class/gpio
kipr/wombat-os pull request #22
Opened 2024-12-13 17:09 UTC by ToberoCat

This pull request updates the flash script to replace the deprecated `/sys/class/gpio` interface with the recommended `libgpiod` library. This change ensures compatibility with the latest Raspberry Pi OS builds, such as Bookworm and newer, where the `/sys/class/gpio` interface is no longer included. The legacy interface is only functional on older builds like Bullseye.

### Motivation
The `/sys/class/gpio` interface has been deprecated since 2015 and been finally removed in recent Debian-based Raspberry Pi OS releases. Debian now recommends using `libgpiod` for GPIO control. To accommodate this change, the flash script has been updated accordingly. 
I noticed this was the case when trying to flash the firmware from Debian bookworm - Hence the change.

### Changes Made
1. Updated the flash script to use `libgpiod` for GPIO pin control.
2. Added a prerequisite for `libgpiod`. This can be installed with:
   ```bash
   sudo apt-get install libgpiod
   ```
3. Verified that the updated script works correctly with the `stm32flash` tool.

### Testing
The updated script was tested on the Wombat board, and the `stm32flash` tool successfully wrote and verified the binary. Below is the output from a successful test:

```
$ ./wallaby_flash
Setting BOOT0 high...
resetting co-processor...
Flashing firmware...
stm32flash -v -S 0x08000000 -w wombat.bin /dev/ttyAMA0
stm32flash 0.5

http://stm32flash.sourceforge.net/

Using Parser : Raw BINARY
Interface serial_posix: 57600 8E1
Version      : 0x31
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0419 (STM32F42xxx/43xxx)
- RAM        : Up to 192KiB  (12288b reserved by bootloader)
- Flash      : Up to 2048KiB (size first sector: 1x16384)
- Option RAM : 65552b
- System RAM : 30KiB
Write to memory
Erasing memory
Wrote and verified address 0x08007d98 (100.00%) Done.

Setting BOOT0 low...
resetting co-processor...
Flashing process completed.
```

2024-12-17 21:05 UTC, tcorbly requested changes
Can you add `libgpiod` as part of the updateFiles/pkgs/installs folder? Now that we are doing USB updates, any additional packages like these will need to be added as a manual option since Wombats aren't always online. The install will also probably need to be included in the update script.

2024-12-17 21:21 UTC, ToberoCat commented
Just to confirm, should I add the bullseye or bookworm .deb file?  
I'll go with the bullseye one since that's what the current wombat uses, but I want to double-check.

2024-12-18 17:54 UTC, tcorbly commented
> Just to confirm, should I add the bullseye or bookworm .deb file? I'll go with the bullseye one since that's what the current wombat uses, but I want to double-check.

Yes, bullseye is what we need for now.

2025-01-08 16:40 UTC, erinharrington-12 commented
Can you edit updateFiles/wombat_update.sh to either dpkg the specific .deb files or edit the script in the appropriate area (below the libkar, pcompiler, libwallaby,botui) to dpkg all files in the pkgs/installs folder?

2025-01-20 16:00 UTC, ToberoCat commented
I now edited the wombat_update.sh and added all dependencies which have to be installed as deb files.
I have now also tested the entire setup on a wombat freshly flashed wombat, which did work.

If you consider merging it, I highly recommend squashing my commits, as I messed up a little with the commits

2025-01-22 21:23 UTC, tcorbly approved these changes

2025-01-22 21:23 UTC, merged